config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

  root "posts#index"

  get '/about', to: 'pages#about'

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]
  get '/logout', to: 'sessions#destroy'
  get '/not_authorized', to: 'pages#not_authorized'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :commentor, class_name: "User", foreign_key: :commentor_id

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :author, class_name: "User", foreign_key: :author_id, optional: true
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
 class User < ApplicationRecord
  include BCrypt

  has_many :posts, foreign_key: :author_id, class_name: "Post"
  has_many :comments, foreign_key: :commentor_id, class_name: "Comment"

  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end
  helper_method :current_user

  def logged_in?
    session[:user_id] != nil
  end
  helper_method :logged_in?

  def authenticate!
    redirect_to new_session_path unless logged_in?
  end
  helper_method :authenticate!

  def authorize!(user)
    redirect_to '/not_authorized' unless authorized?(user)
  end
  helper_method :authorize!

  def authorized?(user)
    current_user == user
  end
  helper_method :authorized?

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 def create
    authenticate!
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.commentor = current_user
    if @comment.save
      flash[:notice] = "You have successfully created a new comment!"
      redirect_to post_path(@post)
    # else
    #   @errors = @comment.errors.full_messages
    #   render 'form'
    end
  end


  def edit
    authenticate!
    find_comment
  end

  def update
    authenticate!
    find_comment
    authorize!(@comment.commentor)
    if @comment.update(comment_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    authenticate!
    find_comment
    authorize!(@comment.commentor)
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :body)
  end

  def find_comment
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def not_authorized
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action -> { authorize!(@post.author)}, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "You have successfully created a new post!"
      current_user.posts << @post
      redirect_to @post
    else
      @errors = @post.errors.full_messages
      render 'new'
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      @errors = @post.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
  # you have to define or explicitly say what parameters you want to allow
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find_by(id: params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      @errors = ["Something bad happened"]
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You signed up successfully!"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="comment-content">
    <span class="comment-body"><%= comment.name %></span>
    <span class="comment-body"><%= comment.body %></span>
    <span class="comment-time"><%= time_ago_in_words(comment.created_at) %> ago</span> by
    <span class="comment-commentor"><%= link_to comment.commentor.username, user_path(comment.commentor) %></span>
    <% if authorized?(comment.commentor) %>
    | <%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %>
    | <%= link_to 'Delete', [comment.post, comment],
                method: :delete,
                remote: true,
                # class: "button",
                data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h3>Edit comment</h3>

<%= render partial: "pages/errors", locals: { errors: @errors } if @errors %>
<%= form_for([@post, @comment]) do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="sidebar">
      <% if !current_user %>
        <div id="button">
          <button class="button"><%= link_to 'Log in', new_session_path %></button>
          <button class="button"><%= link_to 'Sign up', new_user_path %></button>
        </div>
      <% end %>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </div>

    <div id="main_content">
      <div id="header">
        <% if current_user %>
          <div class="buttons">
              <button class="button"><%= link_to "New post", new_post_path %></button>
              <button class="button"><%= link_to "Log out", logout_path %></button>
          </div>
        <% end %>
      </div>
    <!-- </div> -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert") %>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/_errors.html.erb
<ul>
  <% errors.each do |error| %>
    <li><%= error %></li>
  <% end %>

</ul>

app/views/pages/about.html.erb
<h2>Welcome to my blog! I am Andreea.</h2>

app/views/pages/not_authorized.html.erb
<h3>You are not authorized!</h3>

app/views/posts/_form.html.erb
<%= render partial: "pages/errors", locals: { errors: @errors } if @errors %>
<%= form_for @post do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h3>Edit post</h3>
<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<h3>New post</h3>
<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post_content">
  <h3 class="title">
    <%= @post.title %>
  </h3>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago by <%= link_to @post.author.username, user_path %>
    <% if authorized?(@post.author) %>
      | <%= link_to 'Edit', edit_post_path(@post) %>
      | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm:'Are you sure?'} %>
    <% end %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>
  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add a comment</h3>
    <%= render "comments/form" %>
  </div>
</div>

app/views/users/new.html.erb
<h3>Register</h3>

<%= form_for :user, url: '/users' do |f| %>

  <%= render partial: "pages/errors", locals: { errors: @errors } if @errors %>

  <p>
    <%= f.label :username %>
    <%= f.text_field :username%>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit "Sign up" %>
  </p>
<% end %>

app/views/users/show.html.erb
<h3><%= @user.username %>'s profile page</h3>
<% if @posts.any? %>
  <% @posts.each do |post| %>
    <ul>
      <li><%= link_to post.title, post %>
        <p><%= post.created_at.strftime("%B, %d, %y") %></p>
      </li>
    </ul>
  <% end %>
<% end %>